services:
  api:
    image: bulkpaymentserver-api
    ports:
      - "8080:8080"
    env_file:
      - .env

  worker:
    image: paymentprocessor-python
    container_name: paymentprocessor-python
    env_file:
      - .env
    depends_on:
      - api
