apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulkpayment-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bulkpayment-api
  template:
    metadata:
      labels:
        app: bulkpayment-api
    spec:
      containers:
        - name: api
          image: bulkpaymentrcg.azurecr.io/bulkpayment-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
