apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processor-main
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-processor-main
  template:
    metadata:
      labels:
        app: payment-processor-main
    spec:
      containers:
        - name: processor
          image: bulkpaymentrcg.azurecr.io/payment-processor:1.0.0
          imagePullPolicy: Always
          env:
            - name: WORKER_MODE
              value: "main"
          envFrom:
            - secretRef:
                name: payment-secrets
