apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processor-main
spec:
  replicas: 6
  selector:
    matchLabels:
      app: payment-processor-main
  template:
    metadata:
      labels:
        app: payment-processor-main
    spec:
      containers:
        - name: processor
          image: payment-processor
          imagePullPolicy: IfNotPresent
          env:
            - name: WORKER_MODE
              value: "main"
          envFrom:
            - secretRef:
                name: payment-secrets
