apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processor-retry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-processor-retry
  template:
    metadata:
      labels:
        app: payment-processor-retry
    spec:
      containers:
        - name: processor
          image: bulkpaymentrcg.azurecr.io/payment-processor:__TAG__
          env:
            - name: WORKER_MODE
              value: "retry"
          envFrom:
            - secretRef:
                name: payment-secrets
