services:
  api:
    build:
      context: .
      dockerfile: BulkPaymentServer.Api/Dockerfile
    image: api-server
    env_file:
      - .env

  worker-main:
    build:
      context: PaymentProcessor.Python
      dockerfile: Dockerfile
    image: paymentprocessor-python
    env_file:
      - .env
    environment:
      WORKER_MODE: main
    restart: unless-stopped

  worker-retry:
    build:
      context: PaymentProcessor.Python
      dockerfile: Dockerfile
    image: paymentprocessor-python
    env_file:
      - .env
    environment:
      WORKER_MODE: retry
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
